// ============================================================
// PUSH NOTIFICATION PHRASES — All 18 Languages
// ============================================================
// Used by handlers when sending push notifications.
// The recipient's language is fetched from their profile/preferences.

const PUSH_PHRASES = {
  en: {
    sentMessage: 'Sent you a message',
    repliedComment: 'Replied to your comment in the debate',
    joinedDebate: (name) => `${name} has joined the debate`,
    verdictIn: 'The verdict is in',
    newMessage: 'You have a new notification',
    inGroup: (name, group) => `${name} in ${group}`,
    newReplyComment: 'New reply to your comment',
    repliedYourComment: (name) => `${name} replied to your comment`,
    newInCollective: (name) => `${name} commented on a discussion`,
    invitedDebate: (inviterName, title) => `${inviterName} invited you to a debate: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} invited you to a colloquium: "${title}"`,
    pushTestTitle: 'Philosify Test',
    pushTestBody: 'If you see this, push notifications are working!',
  },
  pt: {
    sentMessage: 'Enviou uma mensagem para voce',
    repliedComment: 'Respondeu ao seu comentario no debate',
    joinedDebate: (name) => `${name} entrou no debate`,
    verdictIn: 'O veredito chegou',
    newMessage: 'Voce tem uma nova notificacao',
    inGroup: (name, group) => `${name} em ${group}`,
    newReplyComment: 'Nova resposta ao seu comentario',
    repliedYourComment: (name) => `${name} respondeu ao seu comentario`,
    newInCollective: (name) => `${name} comentou em uma discussao`,
    invitedDebate: (inviterName, title) => `${inviterName} convidou voce para um debate: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} convidou voce para um coloquio: "${title}"`,
    pushTestTitle: 'Teste do Philosify',
    pushTestBody: 'Se voce esta vendo isso, as notificacoes push estao funcionando!',
  },
  es: {
    sentMessage: 'Te envio un mensaje',
    repliedComment: 'Respondio a tu comentario en el debate',
    joinedDebate: (name) => `${name} se unio al debate`,
    verdictIn: 'El veredicto esta listo',
    newMessage: 'Tienes una nueva notificacion',
    inGroup: (name, group) => `${name} en ${group}`,
    newReplyComment: 'Nueva respuesta a tu comentario',
    repliedYourComment: (name) => `${name} respondio a tu comentario`,
    newInCollective: (name) => `${name} comento en una discusion`,
    invitedDebate: (inviterName, title) => `${inviterName} te invito a un debate: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} te invito a un coloquio: "${title}"`,
    pushTestTitle: 'Prueba de Philosify',
    pushTestBody: 'Si ves esto, las notificaciones push funcionan!',
  },
  fr: {
    sentMessage: 'Vous a envoye un message',
    repliedComment: 'A repondu a votre commentaire dans le debat',
    joinedDebate: (name) => `${name} a rejoint le debat`,
    verdictIn: 'Le verdict est arrive',
    newMessage: 'Vous avez une nouvelle notification',
    inGroup: (name, group) => `${name} dans ${group}`,
    newReplyComment: 'Nouvelle reponse a votre commentaire',
    repliedYourComment: (name) => `${name} a repondu a votre commentaire`,
    newInCollective: (name) => `${name} a commente une discussion`,
    invitedDebate: (inviterName, title) => `${inviterName} vous a invite a un debat: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} vous a invite a un colloque: "${title}"`,
    pushTestTitle: 'Test Philosify',
    pushTestBody: 'Si vous voyez ceci, les notifications push fonctionnent!',
  },
  de: {
    sentMessage: 'Hat Ihnen eine Nachricht gesendet',
    repliedComment: 'Hat auf Ihren Kommentar in der Debatte geantwortet',
    joinedDebate: (name) => `${name} ist der Debatte beigetreten`,
    verdictIn: 'Das Urteil ist da',
    newMessage: 'Sie haben eine neue Benachrichtigung',
    inGroup: (name, group) => `${name} in ${group}`,
    newReplyComment: 'Neue Antwort auf Ihren Kommentar',
    repliedYourComment: (name) => `${name} hat auf Ihren Kommentar geantwortet`,
    newInCollective: (name) => `${name} hat eine Diskussion kommentiert`,
    invitedDebate: (inviterName, title) => `${inviterName} hat Sie zu einer Debatte eingeladen: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} hat Sie zu einem Kolloquium eingeladen: "${title}"`,
    pushTestTitle: 'Philosify Test',
    pushTestBody: 'Wenn Sie dies sehen, funktionieren Push-Benachrichtigungen!',
  },
  it: {
    sentMessage: 'Ti ha inviato un messaggio',
    repliedComment: 'Ha risposto al tuo commento nel dibattito',
    joinedDebate: (name) => `${name} si e unito al dibattito`,
    verdictIn: 'Il verdetto e arrivato',
    newMessage: 'Hai una nuova notifica',
    inGroup: (name, group) => `${name} in ${group}`,
    newReplyComment: 'Nuova risposta al tuo commento',
    repliedYourComment: (name) => `${name} ha risposto al tuo commento`,
    newInCollective: (name) => `${name} ha commentato una discussione`,
    invitedDebate: (inviterName, title) => `${inviterName} ti ha invitato a un dibattito: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} ti ha invitato a un colloquio: "${title}"`,
    pushTestTitle: 'Test Philosify',
    pushTestBody: 'Se vedi questo, le notifiche push funzionano!',
  },
  ru: {
    sentMessage: 'Отправил вам сообщение',
    repliedComment: 'Ответил на ваш комментарий в дебатах',
    joinedDebate: (name) => `${name} присоединился к дебатам`,
    verdictIn: 'Вердикт вынесен',
    newMessage: 'У вас новое уведомление',
    inGroup: (name, group) => `${name} в ${group}`,
    newReplyComment: 'Новый ответ на ваш комментарий',
    repliedYourComment: (name) => `${name} ответил на ваш комментарий`,
    newInCollective: (name) => `${name} прокомментировал обсуждение`,
    invitedDebate: (inviterName, title) => `${inviterName} пригласил вас на дебаты: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} пригласил вас на коллоквиум: "${title}"`,
    pushTestTitle: 'Тест Philosify',
    pushTestBody: 'Если вы видите это, push-уведомления работают!',
  },
  hu: {
    sentMessage: 'Uzenetet kuldott neked',
    repliedComment: 'Valaszolt a hozzaszolasodra a vitaban',
    joinedDebate: (name) => `${name} csatlakozott a vitahoz`,
    verdictIn: 'Az itelet megerkezett',
    newMessage: 'Uj ertesitesed van',
    inGroup: (name, group) => `${name} a(z) ${group} csoportban`,
    newReplyComment: 'Uj valasz a hozzaszolasodra',
    repliedYourComment: (name) => `${name} valaszolt a hozzaszolasodra`,
    newInCollective: (name) => `${name} kommentelt egy megbeszelest`,
    invitedDebate: (inviterName, title) => `${inviterName} meghivott egy vitara: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} meghivott egy kollokviomra: "${title}"`,
    pushTestTitle: 'Philosify teszt',
    pushTestBody: 'Ha latod ezt, a push ertesitesek mukodnek!',
  },
  he: {
    sentMessage: 'שלח לך הודעה',
    repliedComment: 'הגיב לתגובה שלך בדיון',
    joinedDebate: (name) => `${name} הצטרף לדיון`,
    verdictIn: 'פסק הדין ניתן',
    newMessage: 'יש לך התראה חדשה',
    inGroup: (name, group) => `${name} ב-${group}`,
    newReplyComment: 'תגובה חדשה לתגובה שלך',
    repliedYourComment: (name) => `${name} הגיב לתגובה שלך`,
    newInCollective: (name) => `${name} הגיב על דיון`,
    invitedDebate: (inviterName, title) => `${inviterName} הזמין אותך לדיון: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} הזמין אותך לקולוקוויום: "${title}"`,
    pushTestTitle: 'בדיקת Philosify',
    pushTestBody: 'אם אתה רואה את זה, התראות push עובדות!',
  },
  zh: {
    sentMessage: '给你发了一条消息',
    repliedComment: '回复了你在辩论中的评论',
    joinedDebate: (name) => `${name} 加入了辩论`,
    verdictIn: '裁决已出',
    newMessage: '你有一条新通知',
    inGroup: (name, group) => `${name} 在 ${group}`,
    newReplyComment: '对你的评论的新回复',
    repliedYourComment: (name) => `${name} 回复了你的评论`,
    newInCollective: (name) => `${name} 评论了一个讨论`,
    invitedDebate: (inviterName, title) => `${inviterName} 邀请你参加辩论："${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} 邀请你参加座谈会："${title}"`,
    pushTestTitle: 'Philosify 测试',
    pushTestBody: '如果你看到这个，推送通知正在工作！',
  },
  ja: {
    sentMessage: 'メッセージを送信しました',
    repliedComment: 'ディベートであなたのコメントに返信しました',
    joinedDebate: (name) => `${name}がディベートに参加しました`,
    verdictIn: '評決が出ました',
    newMessage: '新しい通知があります',
    inGroup: (name, group) => `${name}（${group}）`,
    newReplyComment: 'あなたのコメントへの新しい返信',
    repliedYourComment: (name) => `${name}があなたのコメントに返信しました`,
    newInCollective: (name) => `${name}がディスカッションにコメントしました`,
    invitedDebate: (inviterName, title) => `${inviterName}があなたをディベートに招待しました：「${title}」`,
    invitedColloquium: (inviterName, title) => `${inviterName}があなたをコロキウムに招待しました：「${title}」`,
    pushTestTitle: 'Philosifyテスト',
    pushTestBody: 'これが表示されれば、プッシュ通知が機能しています！',
  },
  ko: {
    sentMessage: '메시지를 보냈습니다',
    repliedComment: '토론에서 당신의 댓글에 답변했습니다',
    joinedDebate: (name) => `${name}님이 토론에 참여했습니다`,
    verdictIn: '평결이 나왔습니다',
    newMessage: '새 알림이 있습니다',
    inGroup: (name, group) => `${name} - ${group}`,
    newReplyComment: '댓글에 새 답변이 있습니다',
    repliedYourComment: (name) => `${name}님이 댓글에 답변했습니다`,
    newInCollective: (name) => `${name}님이 토론에 댓글을 남겼습니다`,
    invitedDebate: (inviterName, title) => `${inviterName}님이 토론에 초대했습니다: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName}님이 콜로키움에 초대했습니다: "${title}"`,
    pushTestTitle: 'Philosify 테스트',
    pushTestBody: '이것이 보이면 푸시 알림이 작동합니다!',
  },
  ar: {
    sentMessage: 'أرسل لك رسالة',
    repliedComment: 'رد على تعليقك في النقاش',
    joinedDebate: (name) => `${name} انضم إلى النقاش`,
    verdictIn: 'صدر الحكم',
    newMessage: 'لديك إشعار جديد',
    inGroup: (name, group) => `${name} في ${group}`,
    newReplyComment: 'رد جديد على تعليقك',
    repliedYourComment: (name) => `${name} رد على تعليقك`,
    newInCollective: (name) => `${name} علق على نقاش`,
    invitedDebate: (inviterName, title) => `${inviterName} دعاك إلى نقاش: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} دعاك إلى ندوة: "${title}"`,
    pushTestTitle: 'اختبار Philosify',
    pushTestBody: 'إذا رأيت هذا، فإن إشعارات الدفع تعمل!',
  },
  hi: {
    sentMessage: 'आपको एक संदेश भेजा',
    repliedComment: 'बहस में आपकी टिप्पणी का जवाब दिया',
    joinedDebate: (name) => `${name} बहस में शामिल हुए`,
    verdictIn: 'फैसला आ गया है',
    newMessage: 'आपकी एक नई सूचना है',
    inGroup: (name, group) => `${name} ${group} में`,
    newReplyComment: 'आपकी टिप्पणी पर नया उत्तर',
    repliedYourComment: (name) => `${name} ने आपकी टिप्पणी का उत्तर दिया`,
    newInCollective: (name) => `${name} ने चर्चा पर टिप्पणी की`,
    invitedDebate: (inviterName, title) => `${inviterName} ने आपको बहस में आमंत्रित किया: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} ने आपको संगोष्ठी में आमंत्रित किया: "${title}"`,
    pushTestTitle: 'Philosify परीक्षण',
    pushTestBody: 'यदि आप यह देख रहे हैं, तो पुश सूचनाएं काम कर रही हैं!',
  },
  fa: {
    sentMessage: 'برایت پیام فرستاد',
    repliedComment: 'به نظر شما در بحث پاسخ داد',
    joinedDebate: (name) => `${name} به بحث پیوست`,
    verdictIn: 'حکم صادر شد',
    newMessage: 'یک اعلان جدید دارید',
    inGroup: (name, group) => `${name} در ${group}`,
    newReplyComment: 'پاسخ جدید به نظر شما',
    repliedYourComment: (name) => `${name} به نظر شما پاسخ داد`,
    newInCollective: (name) => `${name} در بحثی نظر داد`,
    invitedDebate: (inviterName, title) => `${inviterName} شما را به بحث دعوت کرد: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} شما را به سمینار دعوت کرد: "${title}"`,
    pushTestTitle: 'آزمایش Philosify',
    pushTestBody: 'اگر این را می‌بینید، اعلان‌های فشاری کار می‌کنند!',
  },
  nl: {
    sentMessage: 'Heeft je een bericht gestuurd',
    repliedComment: 'Heeft gereageerd op je opmerking in het debat',
    joinedDebate: (name) => `${name} heeft zich bij het debat aangesloten`,
    verdictIn: 'Het oordeel is gevallen',
    newMessage: 'Je hebt een nieuwe melding',
    inGroup: (name, group) => `${name} in ${group}`,
    newReplyComment: 'Nieuw antwoord op je opmerking',
    repliedYourComment: (name) => `${name} heeft op je opmerking gereageerd`,
    newInCollective: (name) => `${name} heeft een discussie becommentarieerd`,
    invitedDebate: (inviterName, title) => `${inviterName} heeft je uitgenodigd voor een debat: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} heeft je uitgenodigd voor een colloquium: "${title}"`,
    pushTestTitle: 'Philosify Test',
    pushTestBody: 'Als je dit ziet, werken push-meldingen!',
  },
  pl: {
    sentMessage: 'Wyslal ci wiadomosc',
    repliedComment: 'Odpowiedzial na twoj komentarz w debacie',
    joinedDebate: (name) => `${name} dolaczyl do debaty`,
    verdictIn: 'Werdykt zostal wydany',
    newMessage: 'Masz nowe powiadomienie',
    inGroup: (name, group) => `${name} w ${group}`,
    newReplyComment: 'Nowa odpowiedz na twoj komentarz',
    repliedYourComment: (name) => `${name} odpowiedzial na twoj komentarz`,
    newInCollective: (name) => `${name} skomentowal dyskusje`,
    invitedDebate: (inviterName, title) => `${inviterName} zaprosil cie do debaty: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} zaprosil cie do kolokvium: "${title}"`,
    pushTestTitle: 'Test Philosify',
    pushTestBody: 'Jesli to widzisz, powiadomienia push dzialaja!',
  },
  tr: {
    sentMessage: 'Sana bir mesaj gonderdi',
    repliedComment: 'Tartismadaki yorumuna cevap verdi',
    joinedDebate: (name) => `${name} tartismaya katildi`,
    verdictIn: 'Karar verildi',
    newMessage: 'Yeni bir bildiriminiz var',
    inGroup: (name, group) => `${name} - ${group}`,
    newReplyComment: 'Yorumunuza yeni cevap',
    repliedYourComment: (name) => `${name} yorumunuza cevap verdi`,
    newInCollective: (name) => `${name} bir tartismaya yorum yapti`,
    invitedDebate: (inviterName, title) => `${inviterName} sizi bir tartismaya davet etti: "${title}"`,
    invitedColloquium: (inviterName, title) => `${inviterName} sizi bir kolokyuma davet etti: "${title}"`,
    pushTestTitle: 'Philosify Testi',
    pushTestBody: 'Bunu goruyorsaniz, push bildirimleri calisiyordur!',
  },
};

/**
 * Get push notification phrase in the recipient's language.
 * @param {string} lang - Recipient's language code
 * @param {string} key - Phrase key
 * @param {...any} args - Arguments for dynamic phrases
 * @returns {string}
 */
export function getPushPhrase(lang, key, ...args) {
  const phrases = PUSH_PHRASES[lang] || PUSH_PHRASES.en;
  const phrase = phrases[key] || PUSH_PHRASES.en[key];
  if (typeof phrase === 'function') return phrase(...args);
  return phrase || PUSH_PHRASES.en[key] || '';
}
